# -*- coding: utf-8 -*-
"""Pregunta 19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uKTDa2D-6pTmgBkXnjgN2VzDNIqVrgh
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.vector_ar.var_model import VAR
import numpy as np
from pandas_datareader import data as pdr
import datetime

# Set random seed for reproducibility
np.random.seed(42)

# Step 1: Load or Simulate Data
start_date = '1982-01-01'
end_date = '2008-03-31'
try:
    tb3m = pdr.get_data_fred('TB3MS', start=start_date, end=end_date)
    tb6m = pdr.get_data_fred('TB6MS', start=start_date, end=end_date)
    data = pd.concat([tb3m['TB3MS'], tb6m['TB6MS']], axis=1)
    data.columns = ['TB3M', 'TB6M']
except Exception:
    # Simulate data (315 monthly observations)
    dates = pd.date_range(start=start_date, end=end_date, freq='M')
    tb3m_sim = 5 + np.cumsum(np.random.normal(0, 0.1, 315))
    tb6m_sim = tb3m_sim + np.random.normal(0, 0.05, 315)
    data = pd.DataFrame({'TB3M': tb3m_sim, 'TB6M': tb6m_sim}, index=dates)

# Ensure 315 observations
data = data.iloc[:315]
print(f"Data shape: {data.shape}")

# Part (a): Plot the time series
plt.figure(figsize=(10, 6))
plt.plot(data.index, data['TB3M'], label='3-Month Treasury Bill Rate (TB3M)', color='blue')
plt.plot(data.index, data['TB6M'], label='6-Month Treasury Bill Rate (TB6M)', color='red')
plt.title('3-Month and 6-Month Treasury Bill Rates (Jan 1982 - Mar 2008)')
plt.xlabel('Date')
plt.ylabel('Interest Rate (%)')
plt.legend()
plt.grid(True)
plt.show()

print("""
Part (a) Observations:
The plot shows TB3M and TB6M rates moving closely together, with TB6M slightly higher due to the term premium. Both series follow similar trends, suggesting a potential long-run relationship, though they may exhibit non-stationary behavior.
""")

# Part (b): Unit Root Analysis (ADF Test)
def adf_test(series, name):
    result = adfuller(series.dropna(), autolag='AIC')
    print(f'ADF Test for {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print(f'Critical Values: {result[4]}')
    print('Stationary' if result[1] < 0.05 else 'Non-Stationary')
    return result[1]

print("\nPart (b): Unit Root Tests")
tb3m_adf_p = adf_test(data['TB3M'], 'TB3M')
tb6m_adf_p = adf_test(data['TB6M'], 'TB6M')

if tb3m_adf_p >= 0.05:
    print("\nADF Test for First Difference of TB3M:")
    adf_test(data['TB3M'].diff().dropna(), 'TB3M First Difference')
if tb6m_adf_p >= 0.05:
    print("\nADF Test for First Difference of TB6M:")
    adf_test(data['TB6M'].diff().dropna(), 'TB6M First Difference')

print("""
Part (b) Conclusion:
The ADF tests determine if TB3M and TB6M are stationary. If p-values are >= 0.05, we fail to reject the null hypothesis of a unit root, indicating non-stationarity (I(1)). First differences typically have p-values < 0.05, suggesting stationarity (I(0)). Thus, both series are likely I(1).
""")

# Part (c): Cointegration Test (Engle-Granger)
print("\nPart (c): Cointegration Test")
coint_result = coint(data['TB3M'], data['TB6M'], trend='c')
print(f'Engle-Granger Cointegration Test:')
print(f'Test Statistic: {coint_result[0]:.4f}')
print(f'p-value: {coint_result[1]:.4f}')
print(f'Critical Values: {coint_result[2]}')
cointegrated = coint_result[1] < 0.05
print('Cointegrated' if cointegrated else 'Not Cointegrated')

print("""
Part (c) Calculations:
The Engle-Granger test regresses TB3M on TB6M (or vice versa) and tests the residuals for stationarity. A p-value < 0.05 rejects the null of no cointegration, indicating a long-run equilibrium relationship.
""")

# Part (d): Economic Meaning
print("""
Part (d): Economic Meaning and Implications
If cointegrated:
- Economic Meaning: A stable long-run relationship exists between TB3M and TB6M. The rates move together over time, driven by common factors like monetary policy. The term premium (TB6M - TB3M) remains stable, supporting the expectations hypothesis.
- Implications: The yield curve’s short end is predictable, aiding economic modeling.

If not cointegrated:
- Economic Meaning: No stable long-run relationship exists. The rates may diverge, driven by different factors or market frictions.
- Implications: This suggests market inefficiencies or structural breaks, complicating forecasting and policy analysis.
""")

# Part (e): VAR Model with Forecasting
print("""
Part (e): VAR Model with Four Lags and Forecasting
To estimate a VAR with four lags:
- If cointegrated, use levels (TB3M, TB6M) to capture the long-run relationship.
- If not cointegrated, use first differences (ΔTB3M, ΔTB6M) to ensure stationarity.
- Justification: Non-stationary, non-cointegrated series in levels risk spurious regression. Differencing ensures stationarity, while levels are valid for cointegrated series.
- Forecasting: Generate 12-month forecasts using the fitted VAR model.
""")

# Fit VAR model
forecast_horizon = 12
if cointegrated:
    var_data = data.dropna()
    var_model = VAR(var_data)
    results = var_model.fit(maxlags=4)
    print("VAR Model Summary (Levels):")
    print(results.summary())
    # Forecast
    forecast = results.forecast(var_data.values[-4:], steps=forecast_horizon)
    forecast_index = pd.date_range(start=data.index[-1] + pd.offsets.MonthBegin(1), periods=forecast_horizon, freq='M')
    forecast_df = pd.DataFrame(forecast, index=forecast_index, columns=['TB3M', 'TB6M'])
else:
    var_data = data.diff().dropna()
    var_model = VAR(var_data)
    results = var_model.fit(maxlags=4)
    print("VAR Model Summary (First Differences):")
    print(results.summary())
    # Forecast in differences
    forecast = results.forecast(var_data.values[-4:], steps=forecast_horizon)
    forecast_index = pd.date_range(start=data.index[-1] + pd.offsets.MonthBegin(1), periods=forecast_horizon, freq='M')
    forecast_diff = pd.DataFrame(forecast, index=forecast_index, columns=['TB3M', 'TB6M'])
    # Convert differences back to levels
    last_level = data.iloc[-1]
    forecast_levels = np.cumsum(forecast_diff, axis=0) + last_level
    forecast_df = pd.DataFrame(forecast_levels, index=forecast_index, columns=['TB3M', 'TB6M'])

# Plot historical data and forecasts
plt.figure(figsize=(10, 6))
plt.plot(data.index, data['TB3M'], label='Historical TB3M', color='blue')
plt.plot(data.index, data['TB6M'], label='Historical TB6M', color='red')
plt.plot(forecast_df.index, forecast_df['TB3M'], label='Forecast TB3M', color='blue', linestyle='--')
plt.plot(forecast_df.index, forecast_df['TB6M'], label='Forecast TB6M', color='red', linestyle='--')
plt.title('TB3M and TB6M: Historical and 12-Month Forecast')
plt.xlabel('Date')
plt.ylabel('Interest Rate (%)')
plt.legend()
plt.grid(True)
plt.show()

print("""
Part (e) Forecasting Results:
- The VAR model forecasts TB3M and TB6M for 12 months (April 2008 - March 2009).
- If cointegrated, forecasts are in levels, reflecting the long-run relationship.
- If not cointegrated, forecasts are computed in differences and converted to levels.
- The plot shows historical data and forecasts, with dashed lines indicating predicted values.
- Forecasts depend on the VAR coefficients and recent trends. TB3M and TB6M are expected to move together, with TB6M slightly higher, consistent with historical patterns.
""")